env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: 
  no-use-before-define:
    - error
    - functions: false
      classes: true

